// BNI 마포홍보관 공용 상수

export const CATEGORIES = [
  { id: 'all', name: '전체', emoji: '📋' },
  { id: 'food', name: '식품/외식', emoji: '🍱' },
  { id: 'health', name: '건강/뷰티', emoji: '💪' },
  { id: 'professional', name: '전문서비스', emoji: '💼' },
  { id: 'edu', name: '교육/컨설팅', emoji: '📚' },
  { id: 'culture', name: '문화/체험', emoji: '🎭' },
  { id: 'digital', name: 'IT/디지털', emoji: '💻' },
  { id: 'etc', name: '기타', emoji: '✨' },
];

export const CHAPTERS = [
  '나이스', '매트릭스', '맥스', '스톤웍스', '애티튜드',
  '유니콘', '제우스', '케이', '타이탄', '탑클래스', '프레즌트',
];

export const SORT_OPTIONS = [
  { id: 'latest', name: '최신순', field: 'created_at' },
  { id: 'popular', name: '인기순', field: 'view_count' },
  { id: 'orders', name: '주문순', field: 'order_count' },
];

export const CHAPTER_DATA = [
  {
    id: 'nice',
    name: '나이스',
    nameEn: 'Nice',
    meeting: '화요일 7:00 AM',
    location: '서울가든호텔',
    members: 22,
    type: 'Hybrid',
    website: 'http://bnimapo.com/mapo-마포-nice',
    bniUrl: 'http://bnimapo.com/ko/chapterdetail?chapterId=IOjXUxcMPfRvrPdFwNDc5w%3D%3D',
  },
  {
    id: 'max',
    name: '맥스',
    nameEn: 'Max',
    meeting: '목요일 7:00 AM',
    location: '라이즈호텔',
    members: 64,
    type: 'In-Person',
    website: 'http://bnimapo.com/mapo-마포-max',
    bniUrl: 'http://bnikorea.com/ko/chapterdetail?chapterId=553QnInYlNYtPSVZVnd5Ag%3D%3D&name=BNI+Max',
  },
  {
    id: 'present',
    name: '프레즌트',
    nameEn: 'Present',
    meeting: '수요일 7:00 AM',
    location: '어반크리에이터스유닛 신촌점',
    members: 32,
    type: 'Hybrid',
    website: 'http://bnimapo.com/mapo-마포-present',
    bniUrl: 'http://bnikorea.com/ko/chapterdetail?chapterId=Rzm%2BnwvWZ5t5FdJOuia9Yw%3D%3D&name=BNI+Present',
  },
  {
    id: 'attitude',
    name: '애티튜드',
    nameEn: 'Attitude',
    meeting: '금요일 7:00 AM',
    location: '라이즈호텔',
    members: 25,
    type: 'Hybrid',
    website: 'http://bnimapo.com/mapo-마포-attitude',
    bniUrl: 'http://bnikorea.com/ko/chapterdetail?chapterId=u6QrkYWFPh1qPE2bltWslw%3D%3D&name=BNI+Attitude',
  },
  {
    id: 'matrix',
    name: '매트릭스',
    nameEn: 'Matrix',
    meeting: '수요일 7:00 AM',
    location: 'BNI Mapo Online',
    members: 34,
    type: 'Permanent Online',
    website: 'http://bnimapo.com/mapo-마포-matrix',
    bniUrl: 'http://bnikorea.com/ko/chapterdetail?chapterId=q6wfNR6uQ7lMZlHnkvsGrg%3D%3D&name=BNI+Matrix',
  },
  {
    id: 'unicorn',
    name: '유니콘',
    nameEn: 'Unicorn',
    meeting: '화요일 7:00 AM',
    location: '라이즈호텔',
    members: 46,
    type: 'In-Person',
    website: 'http://bnimapo.com/mapo-마포-unicorn',
    bniUrl: 'http://bnikorea.com/ko/chapterdetail?chapterId=6%2FDN%2FflvfPt5H%2B7KJGTquw%3D%3D&name=BNI+Unicorn',
  },
  {
    id: 'topclass',
    name: '탑클래스',
    nameEn: 'Topclass',
    meeting: '목요일 7:00 AM',
    location: 'BNI 마포사무실',
    members: 21,
    type: 'Permanent Online',
    website: 'http://bnimapo.com/mapo-마포-topclass',
    bniUrl: 'http://bnikorea.com/ko/chapterdetail?chapterId=qTOaVbnJQ0zPNT1yLaxLrA%3D%3D&name=BNI+Topclass',
  },
  {
    id: 'zeus',
    name: '제우스',
    nameEn: 'Zeus',
    meeting: '수요일 6:30 AM',
    location: 'BNI Mapo Online',
    members: 24,
    type: 'Hybrid',
    website: 'http://bnimapo.com/mapo-마포-zeus',
    bniUrl: 'http://bnikorea.com/ko/chapterdetail?chapterId=AeIqYmE5On3TzqrBLGsRKA%3D%3D&name=BNI+Zeus',
  },
  {
    id: 'k',
    name: '케이',
    nameEn: 'K',
    meeting: '수요일 6:30 AM',
    location: '라이즈호텔',
    members: 30,
    type: 'Hybrid',
    website: 'http://bnimapo.com/mapo-마포-k',
    bniUrl: 'http://bnikorea.com/ko/chapterdetail?chapterId=NSKAjYGXFYQoNRyohxerFQ%3D%3D&name=BNI+K',
  },
  {
    id: 'titan',
    name: '타이탄',
    nameEn: 'TITAN',
    meeting: '화요일 6:30 AM',
    location: '서울가든호텔',
    members: 12,
    type: 'Hybrid',
    website: '',
    bniUrl: 'http://bnikorea.com/ko/chapterdetail?chapterId=On9%2F56iiFJ1fn63Gm5zeuw%3D%3D&name=BNI+TITAN',
  },
  {
    id: 'stoneworks',
    name: '스톤웍스',
    nameEn: 'Stoneworks',
    meeting: '수요일 6:30 AM',
    location: '라이즈호텔',
    members: 20,
    type: 'Hybrid',
    website: '',
    bniUrl: 'http://bnikorea.com/ko/chapterdetail?chapterId=gyhZil0X5Y3El%2FGmsSsFvg%3D%3D&name=BNI+Stoneworks',
  },
];
